version: '3.8'

services:
  api:
    image: dai-app-backend:latest
    container_name: dai-app-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
